from fastapi import FastAPI, UploadFile, File
from pydantic import BaseModel
from backend.memory import thread_document_metadata
from backend.graph import bot
from backend.rag import ingest_pdf
from langchain_core.messages import AIMessageChunk
from langchain_core.messages import HumanMessage
from fastapi.responses import StreamingResponse
import json

app = FastAPI(title="ComeOnChat API")
# ----------------------------
# Request Models
# ----------------------------
class ChatRequest(BaseModel):
    message: str
    thread_id: str


class ChatResponse(BaseModel):
    response: str


# ----------------------------
# Chat Endpoint (non-stream)
# ----------------------------
@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    result = bot.invoke(
        {"messages": [HumanMessage(content=req.message)]},
        config={"configurable": {"thread_id": req.thread_id}},
    )

    return ChatResponse(
        response=result["messages"][-1].content
    )

@app.post("/chat/stream")
def chat_stream(req: ChatRequest):

    def event_generator():
        for msg, metadata in bot.stream(
            {"messages": [HumanMessage(content=req.message)]},
            config={"configurable": {"thread_id": req.thread_id}},
            stream_mode="messages",
        ):

            # Only stream tokens generated by the chat node
            if metadata.get("langgraph_node") == "chat_node":
                if isinstance(msg, AIMessageChunk):
                    if msg.content:
                        yield msg.content

    return StreamingResponse(event_generator(), media_type="text/plain")

# ----------------------------
# PDF Upload Endpoint
# ----------------------------
@app.post("/upload-pdf")
def upload_pdf(thread_id: str, file: UploadFile = File(...)):
    content = file.file.read()

    result = ingest_pdf(
        file_bytes=content,
        thread_id=thread_id,
        filename=file.filename,
    )

    return {
        "status": "success",
        "metadata": result,
    }

# ----------------------------
# Thread Metadata Endpoint
# ----------------------------
@app.get("/thread/{thread_id}/metadata")
def get_metadata(thread_id: str):
    return thread_document_metadata(thread_id)