from fastapi import FastAPI, UploadFile, File
from pydantic import BaseModel
from backend.memory import thread_document_metadata, retrieve_threads
from backend.graph import bot, headingbot
from backend.rag import ingest_pdf
from langchain_core.messages import AIMessageChunk
from langchain_core.messages import HumanMessage, AIMessage
from fastapi.responses import StreamingResponse
import json
import os

app = FastAPI(title="ComeOnChat API")

class ChatRequest(BaseModel):
    message: str
    thread_id: str
    
class ChatResponse(BaseModel):
    response: str

@app.get("/")
def home():
    return {"message": "Chatbot API is running"}


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    result = bot.invoke(
        {"messages": [HumanMessage(content=req.message)]},
        config={"configurable": {"thread_id": req.thread_id}},
    )

    return ChatResponse(
        response=result["messages"][-1].content
    )

@app.post("/chat/stream")
def chat_stream(req: ChatRequest):

    def event_generator():
        for msg, metadata in bot.stream(
            {"messages": [HumanMessage(content=req.message)]},
            config={"configurable": {"thread_id": req.thread_id}},
            stream_mode="messages",
        ):

            # Only stream tokens generated by the chat node
            if metadata.get("langgraph_node") == "chat_node":
                if isinstance(msg, AIMessageChunk):
                    if msg.content:
                        yield msg.content

    return StreamingResponse(event_generator(), media_type="text/plain")

@app.post("/upload-pdf")
def upload_pdf(thread_id: str, file: UploadFile = File(...)):
    try:
        content = file.file.read()

        result = ingest_pdf(
            file_bytes=content,
            thread_id=thread_id,
            filename=file.filename,
        )

        return {
            "status": "success",
            "metadata": result,
        }

    except Exception as e:
        import traceback
        traceback.print_exc()

        return {
            "status": "error",
            "message": str(e)
        }

@app.get("/thread/{thread_id}/metadata")
def get_metadata(thread_id: str):
    return thread_document_metadata(thread_id)

@app.get("/threads")
def get_threads():
    return {"threads": retrieve_threads()}

@app.get("/thread/{thread_id}/messages")
def get_thread_messages(thread_id: str):

    state = bot.get_state(
        config={"configurable": {"thread_id": thread_id}}
    )

    messages = state.values.get("messages", [])

    result = []

    for msg in messages:
        if isinstance(msg, HumanMessage):
            role = "user"
        elif isinstance(msg, AIMessage):
            role = "assistant"
        else:
            continue

        result.append({
            "role": role,
            "content": msg.content
        })

    return result

@app.get("/thread/{thread_id}/title")
def get_thread_title(thread_id: str):
    state = bot.get_state(
        config={"configurable": {"thread_id": thread_id}}
    )
    messages = state.values.get("messages", [])
    user_text = " ".join(m.content for m in messages if isinstance(m, HumanMessage))[:80]
    if not user_text.strip():
        return {"title": "New Chat"}
    prompt = (
        f"Generate a short conversation title "
        f"(3-6 words). Conversation:{user_text}"
    )
    name = headingbot.invoke(prompt)
    return {"title": name.heading}

@app.get("/thread/{thread_id}")
def get_thread(thread_id: str):
    state = bot.get_state(
        config={"configurable": {"thread_id": thread_id}}
    )
    messages = state.values.get("messages", [])
    result = []
    for msg in messages:
        if isinstance(msg, HumanMessage):
            role = "user"
        elif isinstance(msg, AIMessage):
            role = "assistant"
        else:
            continue
        result.append({
            "role": role,
            "content": msg.content
        })
    return {
        "thread_id": thread_id,
        "messages": result,
        "metadata": thread_document_metadata(thread_id)
    }